apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-hello
resources:
- ../../base
images:
 - name: bobjwalker99/hello-containers
   newName: bobjwalker99/hello-containers
   newTag: "0.1.79.1"

patches:
 - target:
      kind: Ingress
      name: hello-ingress-nginx
   path: hello-ingress-nginx.yaml
