apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment  
spec:
  replicas: {{ .Values.hello.image.replicas }}
  selector:
    matchLabels: 
      component: hello-web
  template:
    metadata:
      labels:
        component: hello-web
    spec:
      containers:
        - name: hello-web
          image: bobjwalker99/hello-containers:{{ default .Chart.AppVersion .Values.hello.image.tag }}
          resources:
            requests:
              memory: {{ .Values.hello.image.resources.requests.memory }}
              cpu: {{ .Values.hello.image.resources.requests.cpu }}
            limits:
              memory: {{ .Values.hello.image.resources.limits.memory }}
              cpu: {{ .Values.hello.image.resources.limits.cpu }}
          imagePullPolicy: "Always"
          ports:
           - containerPort: {{ .Values.hello.service.targetPort }}
             name: http-port
          env:
           - name: HELLO_SECRET_PHRASE
             valueFrom:
               secretKeyRef:
                 name: hello-secrets
                 key: homepageDisplay          
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-cluster-ip-service  
spec:
  type: ClusterIP
  selector:
    component: hello-web
  ports:
    - port: {{ .Values.hello.service.port }}
      targetPort: {{ .Values.hello.service.targetPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hello.ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hello-app-cluster-ip-service
              port:
                number: {{ .Values.hello.service.port }}